Feature/posts profile
Studio-024/self-wiser pull request #7
Opened 2022-01-17 01:24 UTC by AlexandreXYZ

2022-01-17 02:53 UTC, k1vz commented
descrição do pull request?

2022-01-17 21:49 UTC, AlexandreXYZ commented
> descrição do pull request?

Tava trovejando muito quando fiz o pull request, só fiz e sai kkkkk

2022-01-19 01:04 UTC, ViniciusGregorine approved these changes
brabo

2022-01-19 14:54 UTC, k1vz commented on src/components/postProfile/index.tsx
> +    post_created: string
troca por "created_at" é oq é geralmente usado

2022-01-19 14:56 UTC, k1vz requested changes
tirando a minha sugestão de mudança no nome da variável, tudo incrivel

2022-01-19 23:50 UTC, merged

2022-01-22 00:36 UTC, k1vz reviewed
lindo